# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KJWorkboxTestDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KJWorkboxTestDemo

pod 'KJWorkbox'
pod 'KJWorkbox/CommonBox'

  target 'KJWorkboxTestDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'KJWorkboxTestDemoUITests' do
    # Pods for testing
  end

end
